In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1,3,5.5],
              [3,4,5]])
a3 = np.array([[[1,2,3],
                [4,5,6],
                
                [7,8,9],
                [10,11,12],
                
                [13,14,15],
                [16,17,18]
               ]])
               

SyntaxError: closing parenthesis ']' does not match opening parenthesis '(' on line 3 (<ipython-input-10-c97fe1e4a382>, line 11)

In [8]:
a3.shape

(1, 6, 3)

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
# Create a DataFrame from numpy array
import pandas as pd
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  5.5
1  3.0  4.0  5.0

In [14]:
col = ["salary","time","experince"]

In [15]:
df.columns(columns , inplace = True)

TypeError: 'RangeIndex' object is not callable

In [26]:
n = np.array([[[[1,2,3]],[[3,4,5]]]])

In [27]:
n.shape

(1, 2, 1, 3)

In [29]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [32]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [34]:
random_array = np.random.randint(0,10 ,size=(3,5))
random_array

array([[7, 8, 7, 5, 2],
       [3, 2, 1, 9, 1],
       [1, 0, 4, 1, 8]])

In [77]:
n = np.array([[[6,7,7,4],
               [6,7,4,5]],
              
              [[8,2,9,7],
               [5,3,5,7]]])

In [78]:
n.ndim

3

In [79]:
n.shape

(2, 2, 4)

In [80]:
n[0]

array([[6, 7, 7, 4],
       [6, 7, 4, 5]])

In [99]:
n1 = np.array([[[2,3,4],
                [4,5,6]],
               
              [[4,6,7],
               [6,7,8]],
               
              [[7,8,5],
               [7,4,7]]
              
              ]
              
              )
              

In [100]:
n1.shape

(3, 2, 3)

In [105]:
n1.ndim

3

In [112]:
n2 = np.array([[[1,3,4]],
               [[3,4,6]],
               [[34,65,7]],
               [[32,45,7]]
              
              
              ]

            )

In [113]:
n2.shape

(4, 1, 3)

In [114]:
n2[2]

array([[34, 65,  7]])

In [119]:
random_array = np.random.randint(0,10 , size = (3,5))
random_array

array([[5, 5, 9, 8, 9],
       [5, 9, 3, 2, 0],
       [1, 8, 7, 4, 8]])

In [121]:
random_array2 = np.random.random((3,5))
random_array2

array([[0.27332427, 0.52623286, 0.42379082, 0.83982776, 0.67154574],
       [0.99413031, 0.48376971, 0.98253163, 0.59453026, 0.22582405],
       [0.08219958, 0.06055618, 0.93627317, 0.08058526, 0.44686473]])

# random seed

In [147]:
# np.random.seed(seed=0)
random_array4 = np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [175]:
np.random.seed(7)
random_array6 = np.random.random((5,3))
random_array6

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [179]:
random_array6 = np.random.random((5,3))
random_array6

array([[0.95546832, 0.68291385, 0.05312869],
       [0.30885268, 0.59259469, 0.23512041],
       [0.964971  , 0.94504822, 0.84840088],
       [0.472324  , 0.84147671, 0.13111064],
       [0.30873366, 0.46299639, 0.7418472 ]])

## Viewing  arrays and metrices

In [184]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
n1

array([[[2, 3, 4],
        [4, 5, 6]],

       [[4, 6, 7],
        [6, 7, 8]],

       [[7, 8, 5],
        [7, 4, 7]]])

In [202]:
n1.shape

(3, 2, 3)

In [200]:
new=n1[:2,1:,1:]
new

array([[[5, 6]],

       [[7, 8]]])

In [199]:
new.shape

(2, 1, 2)

In [201]:
n4 = np.random.randint(10,size=(2,3,4,5))
n4

array([[[[6, 5, 7, 1, 5],
         [4, 4, 9, 9, 0],
         [6, 2, 6, 8, 2],
         [4, 1, 6, 1, 5]],

        [[1, 6, 9, 8, 6],
         [5, 9, 7, 5, 4],
         [9, 6, 8, 1, 5],
         [5, 8, 3, 7, 7]],

        [[9, 4, 7, 5, 9],
         [6, 2, 0, 5, 3],
         [0, 5, 7, 1, 8],
         [4, 9, 0, 2, 0]]],


       [[[7, 6, 2, 9, 9],
         [5, 1, 0, 0, 9],
         [1, 1, 5, 3, 2],
         [0, 4, 8, 7, 1]],

        [[4, 9, 3, 6, 7],
         [1, 0, 2, 7, 0],
         [0, 9, 8, 2, 0],
         [5, 5, 0, 9, 0]],

        [[8, 4, 5, 1, 4],
         [0, 7, 2, 0, 3],
         [9, 8, 3, 7, 1],
         [0, 1, 4, 6, 1]]]])

In [205]:
n4[1,1,:1]

array([[4, 9, 3, 6, 7]])

## Manipulating &  comparing arrays

#  Arithmetic

In [206]:
a1 = np.array([1,2,3])

In [207]:
ones = np.ones(3)

In [209]:
a1 + ones

array([2., 3., 4.])

In [210]:
a1 * ones

array([1., 2., 3.])

In [211]:
a2

array([[1. , 3. , 5.5],
       [3. , 4. , 5. ]])

In [212]:
a1

array([1, 2, 3])

In [214]:
a1*a2

array([[ 1. ,  6. , 16.5],
       [ 3. ,  8. , 15. ]])

In [215]:
np.version

<module 'numpy.version' from 'C:\\Users\\mohamed ahmed\\anaconda3\\lib\\site-packages\\numpy\\version.py'>

In [216]:
np.sqrt(a2)

array([[1.        , 1.73205081, 2.34520788],
       [1.73205081, 2.        , 2.23606798]])

## Aggregation

In [217]:
a1

array([1, 2, 3])

In [218]:
sum(a1)

6

In [219]:
np.sum(a1)

6

 Use python's methods `(sum())` on python datatypes and use Numpy's methos on numpy arrays `(np.sum())`

In [222]:
massive_array = np.random.random(100000)

In [223]:
%timeit sum(massive_array)1
%timeit np.sum(massive_array)

10.3 ms ± 554 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
56.6 µs ± 1.27 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [224]:
a2

array([[1. , 3. , 5.5],
       [3. , 4. , 5. ]])

In [225]:
np.mean(a2)

3.5833333333333335

In [226]:
np.max(a2)

5.5

In [227]:
higher_var_array = np.array([1,100,200,300,4000,5000])
lower_var_array = np.array([2,4,6,8,10])

In [228]:
np.var(higher_var_array) , np.var(lower_var_array)

(4296133.472222221, 8.0)

### Reshaping and transposing

In [229]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [230]:
a3.shape

(1, 6, 3)

In [236]:
r = np.array([[
             [1,2,3]],
             [[3,4,6]],
             
             ],
             [[[43,57,89]],
              [[43,5,7]]
             
             ]])

In [237]:
r.shape

(2, 2, 1, 3)

In [238]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (1,6,3) 

In [239]:
a2.shape , a3.shape

((2, 3), (1, 6, 3))

In [249]:
a3 = np.array([[[1,3,4],[24,56,7],[23,5,76]],
               [[3,4,5],[34,5,6],[34,7,8]],
               
              
              
              ])

In [251]:
a2_reshaped = a2.reshape(2,3,1)
a2_reshaped

array([[[1. ],
        [3. ],
        [5.5]],

       [[3. ],
        [4. ],
        [5. ]]])

In [252]:
a2_reshaped * a3

array([[[  1. ,   3. ,   4. ],
        [ 72. , 168. ,  21. ],
        [126.5,  27.5, 418. ]],

       [[  9. ,  12. ,  15. ],
        [136. ,  20. ,  24. ],
        [170. ,  35. ,  40. ]]])

In [250]:
a3.shape

(2, 3, 3)

In [255]:
# Transpose = switches the axis'
a2.T.shape

(3, 2)

In [254]:
a2.shape

(2, 3)

# Dot product

In [257]:
np.random.seed(0)
mat1 = np.random.randint(10 , size=(5,3))
mat2 = np.random.randint(10 , size=(5,3))


In [258]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [259]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [260]:
mat1 * mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [261]:
 mat1.shape , mat2.shape

((5, 3), (5, 3))

mat2 = mat2.t

In [262]:
mat2 = mat2.T

In [263]:
mat3 = np.dot(mat1,mat2)
mat3

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [264]:
mat3.shape

(5, 5)

## Dot product example(nut butter sales)

In [265]:
np.random.seed(0)
sales_amount = np.random.randint(20 , size=(5,3))

sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [267]:
columns = ["almond butter","peanut butter","cashew butter"]
weekly_sales = pd.DataFrame(sales_amount,
                           index = ["mon","tues","wed","thrus","fri"],
                           columns =columns)

In [269]:
weekly_sales

almond butter  peanut butter  cashew butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thrus              4              6             12
fri                1              6              7

In [270]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [274]:
butter_prices = pd.DataFrame(prices.reshape(1,3) ,
                            index =["price"],
                            columns = columns)
butter_prices

almond butter  peanut butter  cashew butter
price             10              8             12

In [277]:
total_sales = prices.dot(sales_amount.T)

In [278]:
butter_prices

almond butter  peanut butter  cashew butter
price             10              8             12

In [279]:
weekly_sales

almond butter  peanut butter  cashew butter
mon               12             15              0
tues               3              3              7
wed                9             19             18
thrus              4              6             12
fri                1              6              7

In [280]:
butter_prices.shape , weekly_sales.shape

((1, 3), (5, 3))

In [283]:
weekly_sales.T

mon  tues  wed  thrus  fri
almond butter   12     3    9      4    1
peanut butter   15     3   19      6    6
cashew butter    0     7   18     12    7

In [281]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

mon  tues  wed  thrus  fri
price  240   138  458    232  142

In [284]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

almond butter  peanut butter  cashew butter  Total ($)
mon               12             15              0        240
tues               3              3              7        138
wed                9             19             18        458
thrus              4              6             12        232
fri                1              6              7        142

In [286]:
a1

array([1, 2, 3])

In [287]:
a2

array([[1. , 3. , 5.5],
       [3. , 4. , 5. ]])

In [285]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [288]:
a1 == a1

array([ True,  True,  True])

In [289]:
a1 == a2

array([[ True, False, False],
       [False, False, False]])

## 5. Sorting arrays

In [292]:
random_a = np.random.randint(10 , size=(3,5))

In [293]:
np.sort(random_a)

array([[1, 3, 3, 3, 8],
       [0, 1, 7, 9, 9],
       [0, 2, 3, 4, 7]])

In [294]:
a1

array([1, 2, 3])

In [295]:
np.argsort(a1)

array([0, 1, 2], dtype=int64)

In [296]:
np.argmin(a1)

0

In [297]:
random_a

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9],
       [0, 4, 7, 3, 2]])

In [298]:
np.argmax(random_a , axis=0)

array([0, 2, 2, 1, 1], dtype=int64)

In [299]:
np.argmax(random_a , axis=1)

array([0, 3, 2], dtype=int64)

# 16. Turn Images Into NumPy Arrays
  ### Didn't watch it